---
- name: Install specified CVEs on hosts
  hosts: all
  become: true
  tasks:

    - ansible.builtin.set_fact:
        cve_list: "{{ cves | split }}"

    - name: Ensures that yum-utils is installed
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Check if CVEs are available
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 100
      ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} check-update {{ lookup('ansible.builtin.template', './cve.j2') }}"

    - name: Install CVEs
      when: result.rc == 100
      ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} update -y {{ lookup('ansible.builtin.template', './cve.j2') }}"

    - name: Check if system needs reebot
      register: reboot_needed
      changed_when: false
      failed_when: false
      ansible.builtin.command: needs-restarting -r

    - name: Reboot system
      when: "'Reboot is required' in reboot_needed['stdout'] and reboot == 'true'"
      ansible.builtin.reboot:
        reboot_timeout: 3600
