---
# tasks file for roles/cve-patch-rhel
- ansible.builtin.set_fact:
    cve_list: "{{ cves | split }}"

- name: Ensures that yum-utils is installed
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Ensures report file exists
  ansible.builtin.lineinfile:
    path: files/report.csv
    line: "HOSTNAME,CVE,REBOOT REQUIRED"
    create: yes
  delegate_to: localhost
  run_once: true

- name: Check per CVE and fills report data
  ansible.builtin.include_tasks: report_tasks.yml
  loop: "{{ cve_list }}"

- name: Check if CVEs are available
  register: result
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 100
  ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} check-update {{ lookup('ansible.builtin.template', 'cve.j2') }}"

- name: Install CVEs
  when: result.rc == 100
  ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} update -y {{ lookup('ansible.builtin.template', 'cve.j2') }}"

- name: Check if system needs reebot
  register: reboot_needed
  changed_when: false
  failed_when: false
  ansible.builtin.command: needs-restarting -r

- name: Fills Reboot column in report
  delegate_to: localhost
  block:
    - ansible.builtin.replace:
        path: files/report.csv
        regexp: '^({{ ansible_fqdn }},CVE-\d{4}-\d{4,7})$'
        replace: '\g<1>,true'
      when: "'Reboot is required' in reboot_needed['stdout']"

    - ansible.builtin.replace:
        path: files/report.csv
        regexp: '^({{ ansible_fqdn }},CVE-\d{4}-\d{4,7})$'
        replace: '\g<1>,false'
      when: "'Reboot is required' not in reboot_needed['stdout']"

- name: Reboot system
  when: "'Reboot is required' in reboot_needed['stdout'] and reboot == 'true'"
  ansible.builtin.reboot:
    reboot_timeout: 3600

#- name: Send report through mail
#  community.general.mail:
#    host: "{{ mail_smtp_host }}"
#    port: 25
#    subject: "{{ mail_subject }}"
#    body: "{{ mail_body }}"
#    from: "{{ mail_sender }}"
#    to: "{{ mail_recipient }}"
#    attach: files/report.csv
#  delegate_to: localhost
#  run_once: true

- name: Removes report
  ansible.builtin.file:
    path: files/report.csv
    state: absent
  delegate_to: localhost
  run_once: true
