---
- name: Check if CVEs are available (individually)
  register: cve_status
  changed_when: false
  failed_when: cve_status.rc != 0 and cve_status.rc != 100
  ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} check-update --cve {{ item }}"

- name: Add CVE to report
  when: cve_status.rc == 100
  ansible.builtin.lineinfile:
    path: files/report.csv
    line: "{{ ansible_facts['fqdn'] }},{{ item }}"
  delegate_to: localhost
